### ISSUE TITLE
Inconsistent LocalDate format (instead of using array, allow numeric timestamp too)

### ISSUE THREAD

**Issue by lukepalmer** [FasterXML/jackson-datatype-joda#39]
I recently ran across this for LocalDate:

```
    if (provider.isEnabled(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)) {
        // Timestamp here actually means an array of values
        jgen.writeStartArray();
```

This doesn't make sense to me.  A timestamp is a well-defined thing and is not an array.

This can obviously be improved, but how to do it?  Thoughts on one of the options below?  My preference is #1 but I don't know if the array thing is useful to anyone.
1. Make WRITE_DATES_AS_TIMESTAMPS actually write a timestamp.  Eliminate the array-writing behavior.
2. Do 1, but add a new option called WRITE_LOCALDATE_AS_ARRAY in case someone cares about this behavior and wants to opt-in.
3. Add a new option for DONT_WRITE_LOCALDATE_AS_ARRAY that makes WRITE_DATES_AS_TIMESTAMPS behave as expected.  Most compatible, least clean, requires future users of this to discover the special setting to get expected behavior.

**Comment by cowtowncoder** [comment]
Started working on this, and then realizing that:

1. since it's only "Date", with no time, assumptions needed (probably, use midnight?) AND
2. being "Local", no timezone associated.

both of which mean complications for getting timestamp. One could perhaps assume contextual timezone from mapper (which is available), midnight... but that seems like quite a bit of magic.

So, for now, will improve code to make it easy to select based on ARRAY vs NUMBER (`@JsonFormat`), as part of other refactoring, but will NOT change logic.
