### ISSUE TITLE
DateTime serialization should preserve the timezone

### ISSUE THREAD

**Issue by jsravn** [FasterXML/jackson-datatype-joda#43]
I guess it has always been like this, but it doesn't make much sense to me. DateTime is basically a LocalDateTime with a DateTimeZone attached. Generally when people are using DateTime they want time zone info, otherwise they would use a LocalDateTime.

I think as a result of this design decision, many people have to implement custom DateTime functionality to deal with time zone.

What jackson should be doing is to write out the time zone id along with the millis for DateTimes.

**Comment by cowtowncoder** [comment]
As per my comment to the PR #44; Jackson 2.6 adds

    SerializationFeature.WRITE_DATES_WITH_ZONE_ID

which at least allows enabling/disabling of zone-id inclusion over offset.
But I am not quite sure what the representation here should be.

One possibility here is that proposed format (like "0/UTC") would actually be used when writing is (otherwise) by timestamp (numeric). Conversely, when using string representation, we'd use full ISO-8601(-like) String, followed by suffix, perhaps "/zoneid" if that is common enough standard?

**Comment by cowtowncoder** [comment]
As per #44 now implemented for 2.6[.0].
