### ISSUE TITLE
Interval serialization does not respect WRITE_DATES_AS_TIMESTAMPS.

### ISSUE THREAD

**Issue by Afforess** [FasterXML/jackson-datatype-joda#48]
When serializing a JodaTime interval it is always printed in unix-epoch format, regardless of the WRITE_DATES_AS_TIMESTAMPS. An interval is essentially a pair of DateTime objects and should be treated as such when serializing.

**Comment by cowtowncoder** [comment]
One idea here is to support `@JsonFormat(shape=Shape.OBJECT)` to produce JSON Object; and make deserializer support such structure.

**Comment by ssadhoo** [comment]
Is there any fix for this issue or a work around ?

**Comment by Afforess** [comment]
Wowza, this is an old issue. I completely forgot about it. @ssadhoo unfortunately I can't share my workaround - written on company time so I don't own the copyright.

@ssadhoo I can say that it was very trivial and is just a custom serializer for the interval object that wrote out two JodaTime DateTime objects.

**Comment by ssadhoo** [comment]
Thanks a lot @Afforess for the quick response. I will look in to it.

**Comment by cowtowncoder** [comment]
Ok: since there was an improvement, I think what I do here is close this issue: if and when more work is desired it should suggest what further changes would be needed.

Note, specifically, that instead of relying on simple on/off feature, this could and should make use of wider options of `@JsonFormat`, since it may be used:

1. On per-property overrides
2. Per-type defaulting

and allows various "shapes" (NUMBER, STRING, ARRAY, NATURAL) as well as optional `format` too.

**Comment by iNikem** [comment]
@cowtowncoder I am sorry, what improvement exactly do you talk about? From comments I could not understand what was done here.
