### ISSUE TITLE
New versions, no changes

### ISSUE THREAD

**Issue by adrianboimvaser** [FasterXML/jackson-datatype-joda#97]
Looking at https://github.com/FasterXML/jackson-datatype-joda/commits/2.9 I can tell there are no changes since 2.9.1. Why keep pushing new versions?

**Comment by cowtowncoder** [comment]
@adrianboimvaser Going forward please use mailing lists for questions:

https://groups.google.com/forum/#!forum/jackson-user

Short answer however is this: many/most users prefer consistent set of versions to be released as a set instead of having to figure which components might have changes as features. So when, say, `2.9.5` is released due to changes to `jackson-databind` and other components, it would be inconvenient to try to figure out if there is `2.9.5` of various datatype modules or not.
In theory we could nowadays indicate this via `jackson-bom` (and perhaps this is something to consider for Jackson 3.0), but BOM is relatively new addition.
